### ISSUE TITLE
Utilise show et non toggle

### ISSUE THREAD

**Issue by ThibautCuchet** [victorsmits/Fet-map#1]
Avec le toggle, il garde le state donc toutes les deux fois l'interface s'affiche mais vide.
Avec .show() tu n'as pas le problème

https://github.com/victorsmits/Fet-map/blob/8e67e4cf4fc08eb97b760cab1680d48f498983f4/fet.js#L209

**Comment by victorsmits** [comment]
hoo top merci je savais pas ;)
